modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="extra_additions"
version="EE-00.00.038"
displayName="extra_additions"
credits="made with Mcreator(mcreator.net) and hours of screaming into a wall over debugging!"
displayURL="https://sites.google.com/view/extra-edittions/home?authuser=1"
logoFile="logo.png"
authors="twallowhavenstudios"

[[dependencies.extra_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.extra_additions]]
    modId="just_enough_items"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

